### PR TITLE
Update to latest forge and fix mcmod.info

### PR DESCRIPTION
**Pull request by Aleksey-Terzi**

### CODE REVIEW

**Comment by TealNerd** [comment]
Have you tested that this compiles? Also why add the AT?

**Comment by Aleksey-Terzi** [comment]
> Have you tested that this compiles?

Yes it compiles, tested but just little, will do more testing on Devoted today :)

>  Also why add the AT?

Fields RenderGameOverlayEvent.type and RenderWorldLastEvent.partialTicks are now private in latest forge.
Why such name for file?
I'm using naming convention proposed here: http://www.minecraftforge.net/wiki/Using_Access_Transformers
I.e.: modid_at.cfg

**Comment by TealNerd** [comment]
of course they would make the useful fields private smh, aight ill merge it up!

**Comment by Aleksey-Terzi** [comment]
Thanks

**Pull request merged**
